apiVersion: v1
kind: Service
metadata:
  name: fhk-bff-server
  namespace: prod
  labels:
    app: fhk-bff-server
spec:
  type: ClusterIP      # 내부에서만 접근 가능
  selector:
    app: fhk-bff-server
  ports:
    - port: 80          # Service 접속 포트
      targetPort: 4000  # Pod가 실제 듣는 포트
      protocol: TCP
      name: http
