apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhk-bff-server
  namespace: staging
  labels:
    app: fhk-bff-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fhk-bff-server
  template:
    metadata:
      labels:
        app: fhk-bff-server
    spec:
      containers:
        - name: fhk-bff-server
          image: chaeyun430/fhk-bff-server:${GIT_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000